before_script:
  - corepack enable
  - corepack prepare pnpm@latest-8 --activate
  - pnpm config set store-dir .pnpm-store
  - pnpm install

stages:
  - "typecheck"
  - "build"

typecheck:
  only:
    - main
  stage: "typecheck"
  image: node:18.14.0
  script:
    - pnpm run type-check

build site:
  only:
    - main
  image: node:18.14.0
  stage: build
  script:
    - pnpm run build-only
  cache:
    key:
      files:
        - "pnpm-lock.yaml"
    paths:
      - ".pnpm-store"
  artifacts:
    untracked: false
    when: on_success
    expire_in: "1 day"
    paths:
      - "dist"
