<script setup lang="ts">
import { useCentralAdminStore } from '@/apps/central/stores'
import { Field, Form } from 'vee-validate';
import * as yup from 'yup';
import type { ILoginPayload } from '@/shared/types';
import OfficialLogo from '@/shared/assets/official-full-logo.svg'
import { mdiEye, mdiEyeOff } from '@mdi/js'

const schema = yup.object({
  email_or_phone: yup.string().required('wajib diisi'),
  password: yup.string().required('wajib diisi'),
});

const store = useCentralAdminStore();
const { LOGIN_ACTION } = store
const hasLoading = computed(() => LOGIN_ACTION.isLoading)
const loadingAttrs = computed(() => ({
  loading: hasLoading.value,
  disabled: hasLoading.value
}))


const passwordVisibility = ref<boolean>(false);
const togglePasswordVisibility = () => passwordVisibility.value = !passwordVisibility.value


async function onSubmit(payload: any) {
  await LOGIN_ACTION.execute(0, payload as ILoginPayload)
}
</script>

<template>
  <div class="h-100vh d-flex align-center authbg">
    <Form as="v-form" class="mx-auto" :validation-schema="schema" @submit="onSubmit">
      <v-card elevation="0" width="400" height="530" class="d-flex flex-column justify-center fade-in-bck"
        v-bind:="loadingAttrs">

        <div class="d-flex flex-column">
          <v-img class="mx-auto" :src="OfficialLogo" width="64" height="64" />
          <span class="mx-auto mt-3 text-center font-weight-bold text-h3">Masuk</span>
        </div>

        <v-card-item>

          <!-- email or phone -->
          <Field name="email_or_phone" v-slot="{ field, errors }">
            <v-text-field v-bind="field" :error-messages="errors" label="Email / No. HP" class="mt-4 mb-8" required
              density="compact" hide-details variant="outlined" color="primary" />
          </Field>

          <!-- password -->
          <Field name="password" v-slot="{ field, errors }">
            <v-text-field v-bind="field" :error-messages="errors" label="Password" required density="compact"
              variant="outlined" color="primary" hide-details="auto"
              :append-inner-icon="passwordVisibility ? mdiEye : mdiEyeOff" :type="passwordVisibility ? 'text' : 'password'"
              @click:append-inner="togglePasswordVisibility" class="pwdInput" />
          </Field>


          <v-row class="mt-10" no-gutters>
            <v-col class="d-flex justify-start">
              <v-btn color="#000000" variant="plain" to="/">Kembali</v-btn>
            </v-col>
            <v-col class="d-flex justify-end">
              <v-btn color="primary" :elevation="0" type="submit">Masuk</v-btn>
            </v-col>
          </v-row>
        </v-card-item>
      </v-card>
    </Form>

  </div>
</template>
<style lang="scss">
.fade-in-bck {
  -webkit-animation: fade-in-bck 0.6s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
  animation: fade-in-bck 0.6s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2023-5-9 17:43:59
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in-bck
 * ----------------------------------------
 */
@-webkit-keyframes fade-in-bck {
  0% {
    -webkit-transform: translateZ(80px);
    transform: translateZ(80px);
    opacity: 0;
  }

  100% {
    -webkit-transform: translateZ(0);
    transform: translateZ(0);
    opacity: 1;
  }
}

@keyframes fade-in-bck {
  0% {
    -webkit-transform: translateZ(80px);
    transform: translateZ(80px);
    opacity: 0;
  }

  100% {
    -webkit-transform: translateZ(0);
    transform: translateZ(0);
    opacity: 1;
  }
}
</style>


<route lang="yaml">
name : CENTRAL_AUTH_LOGIN
meta : 
    title : ERP Sidek
</route>
