<script setup lang="ts">
import { useDisplay } from 'vuetify';
import { Vue3Lottie } from 'vue3-lottie'
import 'vue3-lottie/dist/style.css'
import { usePerusahaanStore } from '@/apps/central/stores'

const store = usePerusahaanStore()
const { mdAndDown } = useDisplay()
const route = useRoute();
const router = useRouter();
const { ID_PERUSAHAAN } = route.params

const animatingCard = () => {
  // animating card
  const card = document.getElementById('card-looper')
  card!.classList.add('fade-in')
  card!.style!.animationDelay = '100ms'
  card!.classList.add('scale-up-center')

  // animating card item progress bar
  // const cardProgressbar = document.getElementById('card-looper-progressbar')
  // cardProgressbar!.style.animationDelay = '300ms'
  // cardProgressbar!.classList.add('scale-up-hor-center')

  // animating card item text 
  const cardItemText = document.getElementById('card-looper-loading-text')
  cardItemText!.style.animationDelay = '350ms'
  cardItemText!.classList.add('slide-top')

}



const onAnimationLoaded = () => {
  animatingCard()
  store.VIEW_INSTALLASI(ID_PERUSAHAAN as string)
}


</script>

<template>
  <div class="h-100vh d-flex align-center authbg flex-column justify-center">
    <v-card class="authbg fade-in-bck" id="card-looper" :width="mdAndDown ? 300 : 600" variant="flat">
      <Vue3Lottie @on-animation-loaded="onAnimationLoaded"
        animation-link="https://assets5.lottiefiles.com/packages/lf20_ujzt2n1j.json" :height="mdAndDown ? 200 : 600"
        :width="mdAndDown ? 200 : 600" />
      <div id="card-looper-item">

        <template v-if="store.isInstallError == false">
          <div style="margin-top: -30px; height:200px">
            <v-progress-linear :model-value="store.stepProgressIndicator" id="card-looper-progressbar"
              bg-color="blue-grey" color="primary" height="14" />
            <div id="card-looper-loading-text" class="text-center mt-3">
              <span style="font-weight: normal;" :class="{ 'text-h6': mdAndDown, 'text-h3': !mdAndDown }">Menyiapkan Data
                Bisnis Anda </span>
            </div>
          </div>
        </template>

        <template v-else>
          <div style="margin-top: -30px; height: 200px;" id="card-looper-loading-text" class="text-center">
            <div>
              Terjadi Kesahalan Saat Menyiapkan Data Akuntansi Anda
              <br>
              Tekan Tombol Muat Ulang untuk Melanjutkan Proses Installasi
            </div>
            <v-btn class="mt-3 px-10" @click="store.VIEW_INSTALLASI(ID_PERUSAHAAN as string)" size="small" color="error">
              muat ulang
            </v-btn>
          </div>
        </template>




      </div>
    </v-card>
  </div>
</template>

<style scoped>
/* ----------------------------------------------
* Generated by Animista on 2023-3-28 20:37:33
* Licensed under FreeBSD License.
* See http://animista.net/license for more info. 
* w: http://animista.net, t: @cssanimista
* ---------------------------------------------- */

/**
* ----------------------------------------
* animation scale-up-center
* ----------------------------------------
*/

.scale-up-center {
  -webkit-animation: scale-up-center 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
  animation: scale-up-center 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
}

@-webkit-keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
    transform: scale(0.5);
    opacity: 0;
  }

  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
    opacity: 1;
  }
}

@keyframes scale-up-center {
  0% {
    -webkit-transform: scale(0.5);
    transform: scale(0.5);
    opacity: 0;
  }

  100% {
    -webkit-transform: scale(1);
    transform: scale(1);
    opacity: 1;
  }
}

/* ----------------------------------------------
* Generated by Animista on 2023-3-28 20:45:9
* Licensed under FreeBSD License.
* See http://animista.net/license for more info. 
* w: http://animista.net, t: @cssanimista
* ---------------------------------------------- */

/**
* ----------------------------------------
* animation scale-up-hor-center
* ----------------------------------------
*/

.scale-up-hor-center {
  -webkit-animation: scale-up-hor-center 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
  animation: scale-up-hor-center 0.4s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
}

@-webkit-keyframes scale-up-hor-center {
  0% {
    -webkit-transform: scaleX(0.4);
    transform: scaleX(0.4);
  }

  100% {
    -webkit-transform: scaleX(1);
    transform: scaleX(1);
  }
}

@keyframes scale-up-hor-center {
  0% {
    -webkit-transform: scaleX(0.4);
    transform: scaleX(0.4);
  }

  100% {
    -webkit-transform: scaleX(1);
    transform: scaleX(1);
  }
}



/* ----------------------------------------------
* Generated by Animista on 2023-3-28 20:49:25
* Licensed under FreeBSD License.
* See http://animista.net/license for more info. 
* w: http://animista.net, t: @cssanimista
* ---------------------------------------------- */

/**
* ----------------------------------------
* animation slide-top
* ----------------------------------------
*/
.slide-top {
  -webkit-animation: slide-top 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
  animation: slide-top 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}

@-webkit-keyframes slide-top {
  0% {
    -webkit-transform: translateY(-100px);
    transform: translateY(-100px);
  }

  100% {
    -webkit-transform: translateY(0px);
    transform: translateY(0px);
  }
}

@keyframes slide-top {
  0% {
    -webkit-transform: translateY(-100px);
    transform: translateY(-100px);
  }

  100% {
    -webkit-transform: translateY(0px);
    transform: translateY(0px);
  }
}


.fade-in-bck {
  -webkit-animation: fade-in-bck 0.6s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
  animation: fade-in-bck 0.6s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2023-5-9 17:43:59
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in-bck
 * ----------------------------------------
 */
@-webkit-keyframes fade-in-bck {
  0% {
    -webkit-transform: translateZ(80px);
    transform: translateZ(80px);
    opacity: 0;
  }

  100% {
    -webkit-transform: translateZ(0);
    transform: translateZ(0);
    opacity: 1;
  }
}

@keyframes fade-in-bck {
  0% {
    -webkit-transform: translateZ(80px);
    transform: translateZ(80px);
    opacity: 0;
  }

  100% {
    -webkit-transform: translateZ(0);
    transform: translateZ(0);
    opacity: 1;
  }
}
</style>

<route lang="yaml">
name : CENTRAL_AUTH_INSTALLASI
meta : 
    title : ERP Sidek | Installasi Modul
</route>
