/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Appbar: typeof import('./components/Appbar.vue')['default']
    BannerInnerpage: typeof import('./components/BannerInnerpage.vue')['default']
    Demos: typeof import('./components/Demos.vue')['default']
    Features: typeof import('./components/Features.vue')['default']
    HomeBanner: typeof import('./components/HomeBanner.vue')['default']
    ModuleInfo: typeof import('./components/ModuleInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Subscribe: typeof import('./components/Subscribe.vue')['default']
    Testimoni: typeof import('./components/Testimoni.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    Timeline: typeof import('./components/Timeline.vue')['default']
  }
}
