/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArusKasTable: typeof import('./apps/central/components/ArusKasTable.vue')['default']
    ArusKasTableRow: typeof import('./apps/central/components/ArusKasTableRow.vue')['default']
    ChipStatusJurnal: typeof import('./apps/central/components/chip-status-jurnal.vue')['default']
    DateSeriesFilter: typeof import('./apps/central/components/date-series-filter.vue')['default']
    DevSuperFinderPopup: typeof import('./apps/super/components/DevSuperFinderPopup.vue')['default']
    DevToolMemoryUsage: typeof import('./apps/super/components/DevToolMemoryUsage.vue')['default']
    DiskonPembelianForm: typeof import('./apps/central/components/diskon-pembelian-form.vue')['default']
    DiskonPenjualanForm: typeof import('./apps/central/components/diskon-penjualan-form.vue')['default']
    FilterWidget: typeof import('./apps/central/components/filter-widget.vue')['default']
    FolderView: typeof import('./apps/super/components/FolderView.vue')['default']
    FormAkun: typeof import('./apps/super/components/FormAkun.vue')['default']
    FormAkunKategori: typeof import('./apps/super/components/FormAkunKategori.vue')['default']
    FormDiskon: typeof import('./apps/super/components/FormDiskon.vue')['default']
    FormJenisUsaha: typeof import('./apps/super/components/FormJenisUsaha.vue')['default']
    FormKasDataDasar: typeof import('./apps/super/components/FormKasDataDasar.vue')['default']
    FormKategoriBarang: typeof import('./apps/super/components/FormKategoriBarang.vue')['default']
    FormPajak: typeof import('./apps/super/components/FormPajak.vue')['default']
    FormSatuanBarang: typeof import('./apps/super/components/FormSatuanBarang.vue')['default']
    KasPopup: typeof import('./apps/central/components/kas-popup.vue')['default']
    KeuanganKasForm: typeof import('./apps/central/components/keuangan-kas-form.vue')['default']
    KonfirmasiPopup: typeof import('./apps/central/components/konfirmasi-popup.vue')['default']
    KuantitasAwalForm: typeof import('./apps/central/components/kuantitas-awal-form.vue')['default']
    LabaRugiTable: typeof import('./apps/central/components/LabaRugiTable.vue')['default']
    LabaRugiTableRowRecursive: typeof import('./apps/central/components/LabaRugiTableRowRecursive.vue')['default']
    NeracaTable: typeof import('./apps/central/components/NeracaTable.vue')['default']
    NeracaTableRowRecursive: typeof import('./apps/central/components/NeracaTableRowRecursive.vue')['default']
    PajakPembelianForm: typeof import('./apps/central/components/pajak-pembelian-form.vue')['default']
    PajakPenjualanForm: typeof import('./apps/central/components/pajak-penjualan-form.vue')['default']
    PelangganForm: typeof import('./apps/central/components/pelanggan-form.vue')['default']
    PemasokForm: typeof import('./apps/central/components/pemasok-form.vue')['default']
    ProfilePerusahaan: typeof import('./apps/central/components/profile-perusahaan.vue')['default']
    RincianHarga: typeof import('./apps/central/components/rincian-harga.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchCoa: typeof import('./apps/central/components/search-coa.vue')['default']
    SearchFilter: typeof import('./apps/central/components/search-filter.vue')['default']
    SelectRegion: typeof import('./apps/central/components/select-region.vue')['default']
    TableRowCOARecursive: typeof import('./apps/super/components/TableRowCOARecursive.vue')['default']
  }
}
